#%RAML 1.0 NamedExample
value:
   
     
      {  
         "total":3,
         "totalPages":4,
         "page":1,
         "account":[  
            {  
               "customerId": "11101",
               "name": "megha",
               "status":"OPEN",
               "accountId":"135790246",
               "accountType":"AUTOLOAN",
               "displayName":"Loan Account",
               "accountDescriptorId":111,
               "transactionId": "111222333444555",
               "referenceTransactionId": "111222333444556",
               "transactionTimestamp":"11,00,00",
               "amount":5000,
               "nickname":"My Loan Account ",
               "accountNumber":"4561237890",
               "interestRate":3,
               "currency":"INR",
               "transactions":[  
                  {  
                     "transactionType":"TRANSFER",
                     "payee":"megha",
                     "checkNumber":"1234567"
                  },
                  {  
                     "transactionType":"CHECK",
                     "payee":"megha",
                     "checkNumber":"1234568"
                  }
               ]
            },
            {  
               "customerId": "11101",
               "name": "megha",
               "status":"OPEN",
               "accountId":"135790246",
               "accountType":"SAVINGS",
               "displayName":"Savings Account",
               "accountDescriptorId":112,
               "transactionId": "111222333444555",
               "referenceTransactionId": "111222333444556",
               "transactionTimestamp":"12,00,00",
               "amount":10000,
               "nickname":"My Savings Account ",
               "accountNumber":"4561237890",
               "interestRate":3,
               "currency":"INR",
               "transactions":[  
                  {  
                     "transactionType":"TRANSFER",
                     "payee":"supriya",
                     "checkNumber":"1234577"
                  },
                  {  
                     "transactionType":"CHECK",
                     "payee":"supriya",
                     "checkNumber":"234587"
                  }
               ]
            }
         ]
      }
   



                     